### ISSUE TITLE
File Size: If size is not available pre-fetch

### ISSUE THREAD

**Issue by evliu** [robbederks/downzip#8]
is there a way for us to not have to pass in size if this is dynamically pulling files? otherwise, shall 0 bytes be passed in?

**Comment by robbederks** [comment]
Ideally, you should pass the actual (or a good estimate) of the length in. This size is used to give the browser an idea of how large the streamed download will be in total to give the end user a good estimate on the remaining time etc.

On the other hand, the size is used to decide early on if we want to start creating a zip64 instead of a normal zip (which can only be up to 4GB in total).

As long as you are sure the zip will be <4GB and you don't care about the browser progress bar, size of 0 is totally fine.
